### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by PortableGames** [Tschipcraft/deathanimations_test#3]
### Is your feature request related to a problem? Please describe.

Update?

**Comment by Tschipcraft** [comment]
Sadly, I currently do not have much free time available, since I have to prepare for my finals that are in a few weeks. But rest assured, development did not stop, I found some epic tech from other developers that enables me to add player death animations, and I'm working on a better ragdoll system behind the scenes.

<a align="center" href="https://github.com/bradleyq/stable_player_display">
  <picture>
    <source 
      srcset="https://github-readme-stats.vercel.app/api/pin/?username=bradleyq&repo=stable_player_display&theme=github_dark&show_owner=true&border_color=30363d"
      media="(prefers-color-scheme: dark)"
      height=120px
    />
    <source
      srcset="https://github-readme-stats.vercel.app/api/pin/?username=bradleyq&repo=stable_player_display&theme=default&show_owner=true"
      media="(prefers-color-scheme: light), (prefers-color-scheme: no-preference)"
      height=120px
    />
    <img height=120px src="https://github-readme-stats.vercel.app/api/pin/?username=bradleyq&repo=stable_player_display&theme=transparent&show_owner=true" alt="Bradleyq's Light Painter"/>
  </picture> 
</a>
